### ISSUE TITLE
Script fails when Tautulli runs it

### ISSUE THREAD

**Issue by Gosha** [Gosha/tautulli-anidb-scrobbler#1]
Works with `docker exec`, but when tautulli tries to launch the script it fails with:

```
2020-06-28 22:42:23 - DEBUG   :: Thread-1 : Tautulli Notifiers :: Executing script in a new thread.
2020-06-28 22:42:23 - DEBUG   :: Thread-16 : Tautulli Notifiers :: Subprocess returned with status code 1.
2020-06-28 22:42:23 - ERROR   :: Thread-16 : Tautulli Notifiers :: Script error: 
  Python path configuration:
    PYTHONHOME = (not set)
    PYTHONPATH = '/nix/store/2kig8zv9lkjhgspx2vfv8hgjylkypwf8-Tautulli-2.2.4/lib:/nix/store/2kig8zv9lkjhgspx2vfv8hgjylkypwf8-Tautulli-2.2.4:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python27.zip:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/plat-linux2:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/lib-tk:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/lib-old:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/lib-dynload:/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/site-packages:/nix/store/9l6y450mln8h12djw1bq8xc0wr065zcq-python2.7-setuptools-44.0.0/lib/python2.7/site-packages'
    program name = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/bin/python3.8'
    isolated = 0
    environment = 1
    user site = 0
    import site = 1
    sys._base_executable = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/bin/python3.8'
    sys.base_prefix = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***'
    sys.base_exec_prefix = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***'
    sys.executable = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/bin/python3.8'
    sys.prefix = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***'
    sys.exec_prefix = '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***'
    sys.path = [
      '/nix/store/2kig8zv9lkjhgspx2vfv8hgjylkypwf8-Tautulli-2.2.4/lib',
      '/nix/store/2kig8zv9lkjhgspx2vfv8hgjylkypwf8-Tautulli-2.2.4',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python27.zip',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/plat-linux2',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/lib-tk',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/lib-old',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/lib-dynload',
      '/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/site-packages',
      '/nix/store/9l6y450mln8h12djw1bq8xc0wr065zcq-python2.7-setuptools-44.0.0/lib/python2.7/site-packages',
      '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/lib/python38.zip',
      '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/lib/python3.8',
      '/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/lib/python3.8/lib-dynload',
    ]
  Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
  Python runtime state: core initialized
    File "/nix/store/qf9a44q8bmyjjzcajigkljxyahzavpaj-python-2.7.18/lib/python2.7/encodings/__init__.py", line 123
      raise CodecRegistryError,\
                              ^
  SyntaxError: invalid syntax
  
  Current thread 0x00007f78a3418f40 (most recent call first):
  <no Python frame>
```

**Comment by Gosha** [comment]
Looks like python2 and 3 gets mixed up.

**Comment by Gosha** [comment]
If `PYTHONPATH` is unset in `/scripts/anidb_scrobble.sh`, it runs.

But instead dies here:
```
Tautulli Notifiers :: Script error:
    Exception in thread Thread-1:
    Traceback (most recent call last):
        File "/nix/store/n0b076p351ma864q38if4yglsg99hw2s-python3-***-***-***/lib/python3.8/threading.py", line 932, in _bootstrap_inner
            self.run()
        File "/nix/store/4l0mq83r65bdl7cbm8fzn4jidiffccal-python3.8-pyanidb-0.2.1/lib/python3.8/site-packages/pyanidb/hash.py", line 115, in run
            self.hashlist.append(File(f, self.algorithms, self.cache))
        File "/nix/store/4l0mq83r65bdl7cbm8fzn4jidiffccal-python3.8-pyanidb-0.2.1/lib/python3.8/site-packages/pyanidb/hash.py", line 75, in __init__
            self.write_cache()
        File "/nix/store/4l0mq83r65bdl7cbm8fzn4jidiffccal-python3.8-pyanidb-0.2.1/lib/python3.8/site-packages/pyanidb/hash.py", line 91, in write_cache
            self.clear_cache()
        File "/nix/store/4l0mq83r65bdl7cbm8fzn4jidiffccal-python3.8-pyanidb-0.2.1/lib/python3.8/site-packages/pyanidb/hash.py", line 100, in clear_cache
            for name in xattr.list(self.name):
    AttributeError: module 'xattr' has no attribute 'list'
```

, which is an unrelated issue: https://github.com/Gosha/private-nixpkgs/issues/2
